BOT_TOKEN = '5411111410:AAFZywpQhXDFTzCJ1yUVQcc-FQUeye5F05s'
API_ID = '9388817
API_HASH = 'a9b26e132f60095bcd53d1fea29476ad'


# DATOS DEL MOODLE
#USUARIO DEL MOODLE entre las comillas
USUARIO = ''
#CONTRASEÑA DEL MOODLE entre las comillas
PASSWORD = ''
#ID DEL MOODLE
USUARIO_ID = 10182
# PAGINA DEL MOODLE DEBE ESTAR COMO EL EJEMPLO: cursos.edu.uo.cu
MOODLE_URL = 'moodle.uclv.edu.cu'
#TAMAÑO EN LO QUE SE PICARAN LOS ZIP AL SUBIR AL MOODLE
ZIP_MB = 399
# TU ID DE TELEGRAM DENTRO DE LOS CORCHETES
OWNER = [5118129784]

#PONGA AQUI PROXY ENCRIPTADO
proxy = ''

# CUENTA DE MEGA
# GMAIL DE CUENTA DE MEGA
GMAIL_MEGA = 'yanco148@gmail.com'
PASS_MEGA = 'yancarlos1482005'
